import { useCallback, useEffect, useState } from 'react'
import { Download, Loader2, Plus, Sparkles } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '@/context/AuthContext'
import { closeConsultation, createLabRequest, getConsultation, getPatient, listExamTypes, listMedications, runAiSuggestions, savePrescription, updateConsultation } from '@/services/clinical'
import type { ConsultationDetail, LabRequest, PatientDossier } from '@/services/clinical'
import type { LabExamType, Medication } from '@/types/database'
import { downloadPrescriptionPdf } from '@/lib/prescriptionPdf'
import { DemoNotice } from './DoctorPatientsPage'

type Tab = 'clinical' | 'ai' | 'labs' | 'prescription' | 'close'
type PrescriptionDraft = { medicationId: string; medicationName: string; posology: string; duration: string; allergyOverrideReason: string }
type ClinicalFormState = { motif: string; history_of_illness: string; temperature_c: string; blood_pressure: string; pulse_bpm: string; weight_kg: string; height_cm: string; cardio: string; respi: string; digestif: string; neuro: string; autre: string; physical_exam: string }
const tabs: Array<{ id: Tab; label: string }> = [{ id: 'clinical', label: 'Examen clinique' }, { id: 'ai', label: 'Suggestions IA' }, { id: 'labs', label: 'Laboratoire' }, { id: 'prescription', label: 'Prescription' }, { id: 'close', label: 'Clôture' }]

export function DoctorConsultationPage() {
  const { id } = useParams()
  const { user, isDemoMode } = useAuth()
  const navigate = useNavigate()
  const [consultation, setConsultation] = useState<ConsultationDetail | null>(null)
  const [dossier, setDossier] = useState<PatientDossier | null>(null)
  const [medications, setMedications] = useState<Medication[]>([])
  const [examTypes, setExamTypes] = useState<LabExamType[]>([])
  const [tab, setTab] = useState<Tab>('clinical')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [ai, setAi] = useState<unknown>(null)
  const [aiDecisions, setAiDecisions] = useState<Array<{ item: string; decision: 'accepted' | 'ignored' }>>([])
  const [selectedExam, setSelectedExam] = useState('')
  const [prescription, setPrescription] = useState<PrescriptionDraft[]>([])
  const [close, setClose] = useState({ diagnosis: '', deferral_reason: '', follow_up_date: '', follow_up_notes: '' })
  const [form, setForm] = useState<ClinicalFormState>({ motif: '', history_of_illness: '', temperature_c: '', blood_pressure: '', pulse_bpm: '', weight_kg: '', height_cm: '', cardio: '', respi: '', digestif: '', neuro: '', autre: '', physical_exam: '' })

  const load = useCallback(async () => {
    if (!id || isDemoMode) return
    setLoading(true); setError('')
    try {
      const detail = await getConsultation(id)
      setConsultation(detail)
      const patient = await getPatient(detail.patient_id)
      setDossier(patient)
      const systems = (detail.review_of_systems && typeof detail.review_of_systems === 'object' && !Array.isArray(detail.review_of_systems) ? detail.review_of_systems : {}) as Record<string, unknown>
      setForm({ motif: detail.motif || '', history_of_illness: detail.history_of_illness || '', temperature_c: detail.temperature_c?.toString() || '', blood_pressure: detail.blood_pressure || '', pulse_bpm: detail.pulse_bpm?.toString() || '', weight_kg: detail.weight_kg?.toString() || '', height_cm: detail.height_cm?.toString() || '', cardio: String(systems.cardio || ''), respi: String(systems.respi || ''), digestif: String(systems.digestif || ''), neuro: String(systems.neuro || ''), autre: String(systems.autre || ''), physical_exam: detail.physical_exam || '' })
      setAi(detail.ai_suggestions); setAiDecisions(Array.isArray(detail.ai_decisions) ? detail.ai_decisions as Array<{ item: string; decision: 'accepted' | 'ignored' }> : [])
      setClose({ diagnosis: detail.diagnosis || '', deferral_reason: detail.deferral_reason || '', follow_up_date: detail.follow_up_date || '', follow_up_notes: detail.follow_up_notes || '' })
      const [meds, exams] = await Promise.all([listMedications(), listExamTypes()]); setMedications(meds); setExamTypes(exams)
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Consultation inaccessible.') }
    finally { setLoading(false) }
  }, [id, isDemoMode])
  useEffect(() => { void load() }, [load])

  const saveDraft = async () => {
    if (!id) return
    setSaving(true); setError('')
    try {
      const next = await updateConsultation(id, { motif: form.motif || null, history_of_illness: form.history_of_illness || null, temperature_c: numberOrNull(form.temperature_c), blood_pressure: form.blood_pressure || null, pulse_bpm: numberOrNull(form.pulse_bpm), weight_kg: numberOrNull(form.weight_kg), height_cm: numberOrNull(form.height_cm), review_of_systems: { cardio: form.cardio, respi: form.respi, digestif: form.digestif, neuro: form.neuro, autre: form.autre }, physical_exam: form.physical_exam || null, ai_decisions: aiDecisions })
      setConsultation((current) => current ? { ...current, ...next } : current)
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Enregistrement impossible.') }
    finally { setSaving(false) }
  }
  const getSuggestions = async () => { if (!id) return; await saveDraft(); setSaving(true); try { const result = await runAiSuggestions(id); setAi(result.suggestions ?? result) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Suggestions indisponibles.') } finally { setSaving(false) } }
  const submitLab = async () => { if (!id || !selectedExam) return; setSaving(true); try { await createLabRequest({ consultationId: id, examTypeId: selectedExam }); setSelectedExam(''); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Demande impossible.') } finally { setSaving(false) } }
  const isAllergic = (name: string) => dossier?.allergies.some((item) => name.toLowerCase().includes(item.substance.toLowerCase()) || item.substance.toLowerCase().includes(name.toLowerCase())) ?? false
  const submitPrescription = async () => { if (!consultation || !dossier || prescription.length === 0) return; const missingOverride = prescription.some((item) => isAllergic(item.medicationName) && !item.allergyOverrideReason.trim()); if (missingOverride) { setError('Une justification est obligatoire pour un médicament correspondant à une allergie.'); return } setSaving(true); try { await savePrescription({ consultationId: consultation.id, patientId: dossier.id, items: prescription.map((item) => ({ medicationId: item.medicationId || null, medicationName: item.medicationName, posology: item.posology, duration: item.duration || null, allergyOverride: isAllergic(item.medicationName), allergyOverrideReason: item.allergyOverrideReason || null })) }); await downloadPrescriptionPdf({ establishmentName: 'AFRIMED', doctorName: user?.name || 'Médecin', patientName: `${dossier.first_name} ${dossier.last_name}`, patientCode: dossier.access_code, date: new Date().toLocaleDateString('fr-FR'), diagnosis: close.diagnosis, items: prescription.map((item) => ({ medicationName: item.medicationName, posology: item.posology, duration: item.duration })) }); setPrescription([]); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Prescription impossible.') } finally { setSaving(false) } }
  const finish = async () => { if (!id || (!close.diagnosis.trim() && !close.deferral_reason.trim())) { setError('Renseignez un diagnostic ou un motif de report.'); return } setSaving(true); try { await closeConsultation(id, { diagnosis: close.diagnosis || null, deferral_reason: close.deferral_reason || null, follow_up_date: close.follow_up_date || null, follow_up_notes: close.follow_up_notes || null }); navigate('/doctor/consultations') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Clôture impossible.') } finally { setSaving(false) } }

  if (isDemoMode) return <DemoNotice title="Les consultations nécessitent Supabase." />
  if (loading && !consultation) return <div className="card text-sm text-primary/60"><Loader2 className="mr-2 inline h-4 w-4 animate-spin" />Chargement de la consultation…</div>
  if (!consultation || !dossier) return <div className="card text-sm text-red-700">{error || 'Consultation introuvable.'}</div>
  const aiItems = toSuggestionItems(ai)
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold text-primary">Consultation</h1><p className="mt-1 text-sm text-primary/60">{dossier.last_name} {dossier.first_name} · {dossier.access_code}</p></div><button type="button" onClick={() => void saveDraft()} disabled={saving || consultation.status === 'closed'} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'Enregistrement…' : 'Enregistrer'}</button></div>{error && <div className="card text-sm text-red-700">{error}</div>}<div className="flex overflow-x-auto border-b border-primary/15">{tabs.map((item) => <button key={item.id} type="button" onClick={() => setTab(item.id)} className={`shrink-0 px-4 py-3 text-sm font-semibold ${tab === item.id ? 'border-b-2 border-secondary text-primary' : 'text-primary/55'}`}>{item.label}</button>)}</div>
    {tab === 'clinical' && <ClinicalForm form={form} setForm={setForm} />}
    {tab === 'ai' && <div className="card space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-primary">Suggestions IA</h2><p className="mt-1 text-sm text-primary/60">Aide à la décision, à valider par le médecin.</p></div><button type="button" onClick={() => void getSuggestions()} disabled={saving} className="inline-flex items-center gap-2 rounded-lg border border-secondary px-4 py-2 text-sm font-semibold text-secondary"><Sparkles className="h-4 w-4" />Suggestions IA</button></div>{aiItems.length === 0 ? <p className="text-sm text-primary/60">Aucune suggestion générée.</p> : <div className="space-y-3">{aiItems.map((item) => <div key={item} className="rounded-lg border border-primary/10 p-3"><p className="text-sm text-primary">{item}</p><div className="mt-2 flex gap-2">{(['accepted', 'ignored'] as const).map((decision) => <button key={decision} type="button" onClick={() => setAiDecisions((values) => [...values.filter((value) => value.item !== item), { item, decision }])} className={`rounded px-3 py-1 text-xs font-semibold ${aiDecisions.find((value) => value.item === item)?.decision === decision ? 'bg-primary text-white' : 'bg-primary/5 text-primary'}`}>{decision === 'accepted' ? 'Accepter' : 'Ignorer'}</button>)}</div></div>)}</div>}</div>}
    {tab === 'labs' && <LabPanel examTypes={examTypes} selected={selectedExam} setSelected={setSelectedExam} onSubmit={submitLab} requests={consultation.labRequests} busy={saving} />}
    {tab === 'prescription' && <PrescriptionPanel medications={medications} items={prescription} setItems={setPrescription} isAllergic={isAllergic} onSubmit={submitPrescription} busy={saving} />}
    {tab === 'close' && <div className="card space-y-4"><h2 className="font-semibold text-primary">Clôturer la consultation</h2><p className="text-sm text-primary/60">Un diagnostic ou un motif de report est obligatoire.</p><label className="block text-sm font-medium text-primary">Diagnostic<textarea value={close.diagnosis} onChange={(e) => setClose((value) => ({ ...value, diagnosis: e.target.value }))} className="mt-1 min-h-24 w-full rounded-lg border border-primary/15 px-3 py-2" /></label><label className="block text-sm font-medium text-primary">Motif de report<textarea value={close.deferral_reason} onChange={(e) => setClose((value) => ({ ...value, deferral_reason: e.target.value }))} className="mt-1 min-h-20 w-full rounded-lg border border-primary/15 px-3 py-2" /></label><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-primary">Date de suivi<input type="date" value={close.follow_up_date} onChange={(e) => setClose((value) => ({ ...value, follow_up_date: e.target.value }))} className="mt-1 w-full rounded-lg border border-primary/15 px-3 py-2" /></label><label className="text-sm font-medium text-primary">Notes de suivi<textarea value={close.follow_up_notes} onChange={(e) => setClose((value) => ({ ...value, follow_up_notes: e.target.value }))} className="mt-1 min-h-20 w-full rounded-lg border border-primary/15 px-3 py-2" /></label></div><button type="button" onClick={() => void finish()} disabled={saving || consultation.status === 'closed'} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">Clôturer la consultation</button></div>}
  </div>
}

function ClinicalForm({ form, setForm }: { form: ClinicalFormState; setForm: React.Dispatch<React.SetStateAction<ClinicalFormState>> }) { const input = (key: keyof ClinicalFormState, label: string, type = 'text') => <label className="text-sm font-medium text-primary">{label}<input type={type} value={form[key]} onChange={(e) => setForm((value) => ({ ...value, [key]: e.target.value }))} className="mt-1 w-full rounded-lg border border-primary/15 px-3 py-2 font-normal" /></label>; return <div className="space-y-4"><div className="card grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-primary">Motif<textarea value={form.motif} onChange={(e) => setForm((value) => ({ ...value, motif: e.target.value }))} className="mt-1 min-h-24 w-full rounded-lg border border-primary/15 px-3 py-2 font-normal" /></label><label className="text-sm font-medium text-primary">Histoire de la maladie<textarea value={form.history_of_illness} onChange={(e) => setForm((value) => ({ ...value, history_of_illness: e.target.value }))} className="mt-1 min-h-24 w-full rounded-lg border border-primary/15 px-3 py-2 font-normal" /></label></div><div className="card"><h2 className="mb-4 font-semibold text-primary">Constantes</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{input('temperature_c', 'Température °C', 'number')}{input('blood_pressure', 'Tension artérielle')}{input('pulse_bpm', 'Pouls / min', 'number')}{input('weight_kg', 'Poids kg', 'number')}{input('height_cm', 'Taille cm', 'number')}</div></div><div className="card"><h2 className="mb-4 font-semibold text-primary">Revue des systèmes</h2><div className="grid gap-3 md:grid-cols-2">{(['cardio', 'respi', 'digestif', 'neuro', 'autre'] as const).map((key) => <label key={key} className="text-sm font-medium capitalize text-primary">{key}<textarea value={form[key]} onChange={(e) => setForm((value) => ({ ...value, [key]: e.target.value }))} className="mt-1 min-h-20 w-full rounded-lg border border-primary/15 px-3 py-2 font-normal" /></label>)}</div></div><div className="card"><label className="block text-sm font-medium text-primary">Examen physique<textarea value={form.physical_exam} onChange={(e) => setForm((value) => ({ ...value, physical_exam: e.target.value }))} className="mt-1 min-h-32 w-full rounded-lg border border-primary/15 px-3 py-2 font-normal" /></label></div></div> }
function LabPanel({ examTypes, selected, setSelected, onSubmit, requests, busy }: { examTypes: LabExamType[]; selected: string; setSelected: (value: string) => void; onSubmit: () => Promise<void>; requests: LabRequest[]; busy: boolean }) { return <div className="card"><h2 className="font-semibold text-primary">Demandes d’examens</h2><div className="mt-4 flex gap-2"><select value={selected} onChange={(e) => setSelected(e.target.value)} className="flex-1 rounded-lg border border-primary/15 px-3 py-2 text-sm"><option value="">Sélectionner un examen</option>{examTypes.map((exam) => <option key={exam.id} value={exam.id}>{exam.name}</option>)}</select><button type="button" onClick={() => void onSubmit()} disabled={!selected || busy} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">Créer la demande</button></div><div className="mt-5 divide-y divide-primary/10">{requests.length === 0 ? <p className="py-3 text-sm text-primary/60">Aucune demande d’examen.</p> : requests.map((request) => <div key={request.id} className="py-3"><p className="font-medium text-primary">{request.lab_exam_types?.name || 'Examen de laboratoire'} <span className="ml-2 text-xs text-primary/60">{request.status}</span></p>{request.result_text && <p className="mt-1 text-sm text-primary/70">{request.result_text}</p>}</div>)}</div></div> }
function PrescriptionPanel({ medications, items, setItems, isAllergic, onSubmit, busy }: { medications: Medication[]; items: PrescriptionDraft[]; setItems: React.Dispatch<React.SetStateAction<PrescriptionDraft[]>>; isAllergic: (name: string) => boolean; onSubmit: () => Promise<void>; busy: boolean }) { const add = () => setItems((current) => [...current, { medicationId: '', medicationName: '', posology: '', duration: '', allergyOverrideReason: '' }]); return <div className="card"><div className="flex justify-between"><h2 className="font-semibold text-primary">Prescription</h2><button type="button" onClick={add} className="inline-flex items-center gap-1 text-sm font-semibold text-secondary"><Plus className="h-4 w-4" />Ajouter</button></div>{items.map((item, index) => <div key={index} className="mt-4 rounded-lg border border-primary/10 p-3"><div className="grid gap-3 md:grid-cols-3"><select value={item.medicationId} onChange={(e) => { const medication = medications.find((value) => value.id === e.target.value); setItems((current) => current.map((value, i) => i === index ? { ...value, medicationId: e.target.value, medicationName: medication?.name || '', posology: medication?.default_posology || value.posology } : value)) }} className="rounded-lg border border-primary/15 px-3 py-2 text-sm"><option value="">Médicament</option>{medications.map((medication) => <option key={medication.id} value={medication.id}>{medication.name}</option>)}</select><input placeholder="Posologie" value={item.posology} onChange={(e) => setItems((current) => current.map((value, i) => i === index ? { ...value, posology: e.target.value } : value))} className="rounded-lg border border-primary/15 px-3 py-2 text-sm" /><input placeholder="Durée" value={item.duration} onChange={(e) => setItems((current) => current.map((value, i) => i === index ? { ...value, duration: e.target.value } : value))} className="rounded-lg border border-primary/15 px-3 py-2 text-sm" /></div>{isAllergic(item.medicationName) && <div className="mt-3 rounded bg-red-50 p-3 text-sm text-red-800">Allergie potentielle signalée. <input placeholder="Justification de l’exception obligatoire" value={item.allergyOverrideReason} onChange={(e) => setItems((current) => current.map((value, i) => i === index ? { ...value, allergyOverrideReason: e.target.value } : value))} className="mt-2 w-full rounded border border-red-200 px-3 py-2" /></div>}<button type="button" onClick={() => setItems((current) => current.filter((_, i) => i !== index))} className="mt-2 text-xs font-semibold text-red-700">Retirer</button></div>)}{items.length === 0 && <p className="mt-4 text-sm text-primary/60">Aucun médicament ajouté.</p>}<button type="button" onClick={() => void onSubmit()} disabled={busy || !items.length} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white"><Download className="h-4 w-4" />Enregistrer et télécharger le PDF</button></div> }
function numberOrNull(value: string) { return value.trim() === '' ? null : Number(value) }
function toSuggestionItems(value: unknown): string[] { if (Array.isArray(value)) return value.map((item) => typeof item === 'string' ? item : JSON.stringify(item)); if (value && typeof value === 'object') return Object.entries(value as Record<string, unknown>).flatMap(([key, item]) => Array.isArray(item) ? item.map((entry) => `${key} : ${typeof entry === 'string' ? entry : JSON.stringify(entry)}`) : [`${key} : ${typeof item === 'string' ? item : JSON.stringify(item)}`]); return [] }
